[package]
name = "rust-psp-tetris"
version = "0.1.0"
authors = ["Paul Sajna <sajattack@gmail.com>"]
edition = "2018"

[dependencies]
psp = { path = "../../psp" }

[profile.release]
opt-level = 3
lto = true
